### ISSUE TITLE
Empty files issue

### ISSUE THREAD

**Issue by nunotexbsd** [babarot/gomi#68]
Hello,

How do gomi handle and should handle empty files?

Example:

```
$ touch EMPTY NOTEMPTY
$ echo "stuff" > NOTEMPTY
$ gomi EMPTY NOTEMPTY
$ gomi -b

│ NOTEMPTY
│ 7 seconds ago • /tmp
```

empty file is lost.

Thanks

**Comment by babarot** [comment]
Please check the configuration file (`~/.config/gomi/config.yaml`).  
By default, it should be set to hide empty files and directories.  

```
history:
  exclude:
    size:
      min: 0KB       # Exclude empty files
      max: 10GB      # Exclude files larger than 10GB
```
