### ISSUE TITLE
filter color customisation

### ISSUE THREAD

**Issue by zencrab** [babarot/gomi#98]
First, I would like to show my appreciation by say thank you for this amazing program. I just love it.

Down to business, the issue I am encountering is the customisation of the filter in the `--restore` menu. I tweaked gomi to make it look just like I like it (catppuccin theme) but the filter is not among the options to customise.

Also, I would love to be able to change the color of the subtext, not in the filter option, but more in the normal view.

![Image](https://github.com/user-attachments/assets/a261fbee-3d58-4cdb-bbb1-46c67a0bbe2d)

I also added a PR to [tldr](https://github.com/tldr-pages/tldr/pull/16166), to add this amazing tool on their page, and please feel free to contribute to it if you think I missed something.

**Comment by babarot** [comment]
Hi @zencrab

Thank you for the feature request and your kind words about gomi! This feature has been implemented and is now available!

You can now customize the filter prompt colors in the restore menu (`gomi -b`) through your configuration file. Two new styling options have been added to the `list_view` section:

```yaml
ui:
  style:
    list_view:
      filter_match: "#F39C12"   # Color of matched text when searching
      filter_prompt: "#7AA2F7"  # Color of the "Filter:" prompt text
```

Thanks again for the suggestion and for contributing to the tldr pages! Let me know if you have any questions or if there are
other customization features you'd like to see. 😊
